version: '3.5'

services: 
    machinaris:
        container_name: machinaris
        image: ghcr.io/hereisderek/machinaris
        restart: unless-stopped
        tty: true
        ports:
        - "8446:8444"
        - "8926:8926"
        volumes:
        - "./data:/root/.chia:rw"
        - "./keyfile:/root/.chia/mnemonic.txt:ro"
        - "~/.ssh/id_rsa:/id_rsa:ro"
        - "/path/to/scratch:/plotting:rw"
        - "/path/to/storage:/plots:rw"
        environment:
        - TZ=Pacific/Auckland
        - "PLOTMAN_GIT_URL=https://github.com/hereisderek/plotman@main"
        - "AUTO_PLOT=true"
